sudo: false

language: android

jdk: oraclejdk8

env:
  global:
    - ANDROID_TARGET=android-25
    - ANDROID_BUILD_TOOLS_VERSION=25.0.0
    - ANDROID_ABI=armeabi-v7a

notifications:
  email:
    - brandon.michael.hogan@gmail.com
  slack: 
    - liftscout:Y8AEaVOpBBcCJWwR2HY9FcnF

android:
  components:
    - tools
    - build-tools-$ANDROID_BUILD_TOOLS_VERSION
    - $ANDROID_TARGET
    - extra-google-google_play_services
    - extra-android-support
    - extra
  
# safelist
branches:
  only:
  - master
  - develop
  - release

licenses:
  - android-sdk-license-.+
  - '.+'

before_install:
 - chmod +x gradlew
 - mkdir "$ANDROID_HOME/licenses" || true
 - echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_HOME/licenses/android-sdk-license"
 - echo -e "\n84831b9409646a918e30573bab4c9c91346d8abd" > "$ANDROID_HOME/licenses/android-sdk-preview-license"
 - echo yes | android update sdk --all --filter build-tools-$ANDROID_BUILD_TOOLS_VERSION --no-ui --force

# Emulator Management: Create, Start and Wait
before_script:
  - echo no | android create avd --force -n test -t android-19 --abi $ANDROID_ABI
  - emulator -avd test -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &

script: 
  - ./gradlew clean check connectedDebugAndroidTest
  #- ./gradlew check
  #- ./gradlew testDebugUnitTestCoverage

after_success:
  - bash <(curl -s https://codecov.io/bash)

after_failure: "cat $TRAVIS_BUILD_DIR/app/build/outputs/lint-results-debug.xml"