language: android
sudo: required
jdk: oraclejdk8

env:
  matrix:
    - ANDROID_TARGET=android-22 ANDROID_ABI=armeabi-v7a

notifications:
  email:
    - brandon.michael.hogan@gmail.com

android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    - platform-tools
    - tools

    # The BuildTools version used by your project
    - build-tools-25.0.2

    # The SDK version used to compile your project
    - android-22
    - android-25

    # Additional components
    #- extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    #- addon-google_apis-google-19

    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    - sys-img-armeabi-v7a-android-22
    - sys-img-armeabi-v7a-android-25
  
# safelist
branches:
  only:
  - master
  - develop
  - release

before_install:
 - chmod +x gradlew

# Emulator Management: Create, Start and Wait
# No point running an emulator if I am only making unit tests (mocked)
# before_script:
#   - echo no | android create avd --force -n test -t android-21 --abi armeabi-v7a
#   - emulator -avd test -no-skin -no-audio -no-window &
#   - android-wait-for-emulator
#   - adb shell input keyevent 82 &

script: 
  - echo "Travis branch is $TRAVIS_BRANCH"
  - echo "Travis branch is in pull request $TRAVIS_PULL+REQUEST"
  - ./gradlew testDebug

after_success:
  - bash <(curl -s https://codecov.io/bash)

after_failure: "cat $TRAVIS_BUILD_DIR/app/build/outputs/lint-results-debug.xml"